services:
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: mysql:9.0
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${DATABASE_HOST}", "-u", "root", "-p${DATABASE_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data: