# Generated by Django 5.1.3 on 2024-12-01 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
